// All categories for our application
export const categories = [
  "Housing",
  "Transportation",
  "Food",
  "Personal Care",
  "Healthcare",
  "Insurance",
  "Clothing",
  "Education",
  "Debt",
  "Investment",
  "Entertainment",
  "Miscellaneous",
  "Salary",
  "Freelance",
  "Investment",
  "Interest",
  "Capital Gains",
  "Awards",
  "Coupons",
  "Grants",
  "Lottery",
  "Rental",
  "Scholarship",
];
